  
version: "3.4"

services:
  jaeger: 
    image: jaegertracing/all-in-one:1.18
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  
  app1-without-jaeger:
    build: ./src/Application1
    image: app1
    environment: 
      - JAEGER_SAMPLER_PARAM=0
      - JAEGER_SERVICE_NAME=app1-without-jaeger
      - JAEGER_AGENT_HOST=jaeger
      - Application2Url=http://app2
    ports:
      - "8081:80"

  app1-with-jaeger:
    build: ./src/Application1
    image: app1
    environment: 
      - JAEGER_AGENT_HOST=jaeger
      - Application2Url=http://app2
    ports:
      - "8082:80"

  app2:
    build: ./src/Application2
    image: app2
    environment: 
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - "8083:80"
